import os
import argparse
import re
import sys

def generate_properties_list(base_dir):
    prop_gen_path = os.path.join(base_dir, "properties.gen")
    
    properties = set()
    
    # 1. Read properties.gen (for generated property parsers)
    if os.path.exists(prop_gen_path):
        with open(prop_gen_path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if ':' in line:
                    name_part = line.split(':', 1)[0].strip()
                    if 'GENERIC' in line:
                        continue
                    prop_name = name_part.replace('_', '-')
                    properties.add(prop_name)
    else:
        print(f"Warning: properties.gen not found at {prop_gen_path}")
    
    # 2. Scan directory for handwritten property parsers
    exclude_files = {
        "css_property_parser_gen.c", 
        "properties.c", 
        "propstrings.c", 
        "utils.c"
    }
    
    if os.path.exists(base_dir):
        for filename in os.listdir(base_dir):
            if filename.endswith(".c") and filename not in exclude_files:
                if filename.startswith("autogenerated"):
                    continue
                
                name = filename[:-2] # remove .c
                prop_name = name.replace('_', '-')
                properties.add(prop_name)
    else:
         print(f"Warning: Directory not found at {base_dir}")
    
    return sorted(list(properties))

def format_properties_list(props):
    lines = []
    lines.append("        var supportedProperties = [")
    
    current_line = "            "
    for i, prop in enumerate(props):
        item = f'"{prop}"'
        if i < len(props) - 1:
            item += ", "
        
        if len(current_line) + len(item) > 80:
            lines.append(current_line)
            current_line = "            " + item
        else:
            current_line += item
            
    lines.append(current_line)
    lines.append("        ];")
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="Generate CSS properties list for polyfill.js")
    parser.add_argument("--libcss-dir", required=True, help="Path to libcss properties directory")
    parser.add_argument("--template", required=True, help="Path to template polyfill.js")
    parser.add_argument("--output", required=True, help="Path to output polyfill.js")
    
    args = parser.parse_args()
    
    props = generate_properties_list(args.libcss_dir)
    formatted_list = format_properties_list(props)
    
    try:
        with open(args.template, 'r') as f:
            content = f.read()
        
        # Regex to replace the supportedProperties array
        # Matches: var supportedProperties = [ ... ];
        # Use re.DOTALL to match across lines
        pattern = r"var supportedProperties = \[.*?\];"
        
        if re.search(pattern, content, flags=re.DOTALL):
            new_content = re.sub(pattern, formatted_list, content, flags=re.DOTALL)
        else:
            print("Appending CSS.supports polyfill.")
            new_content = content + "\n\n// CSS.supports polyfill\n"
            new_content += "if (typeof CSS === 'undefined') {\n    this.CSS = {};\n}\n"
            new_content += "if (typeof CSS.supports === 'undefined') {\n    (function() {\n"
            new_content += "        // List of properties generated by src/content/handlers/javascript/duktape/gen_css_props.py\n"
            new_content += "        // Run that script to update this list when LibCSS properties change.\n"
            new_content += formatted_list + "\n"
            new_content += """
        CSS.supports = function(ident, val) {
            if (arguments.length === 0) return false;
            
            var prop;
            if (arguments.length === 1) {
                var s = ident.toString();
                // Simple check for (prop: val) or prop: val
                if (s.indexOf('(') === 0 && s.lastIndexOf(')') === s.length - 1) {
                    s = s.substring(1, s.length - 1);
                }
                var parts = s.split(':');
                if (parts.length >= 2) {
                    prop = parts[0].trim().toLowerCase();
                } else {
                    prop = s.trim().toLowerCase();
                }
            } else {
                prop = ident.toString().toLowerCase();
            }
            
            return supportedProperties.indexOf(prop) !== -1;
        };
    })();
}
if (typeof CSS.escape === 'undefined') {
    CSS.escape = function(s) { return s; }; // Minimal implementation
}
"""

        # Ensure directory exists
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        
        with open(args.output, 'w') as f:
            f.write(new_content)
            
    except Exception as e:
        print(f"Error processing file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
